language: python
before_script:
  - pip install flake8
script:
  - python setup.py test
  - git clean -dfx
  - flake8 --ignore=E501 .
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
