language: python
install:
  - pip install flake8
script:
  - python setup.py test
  - flake8 tsuru
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
